// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpвateUsers(ctx context.Context, arg UpвateUsersParams) (User, error)
}

var _ Querier = (*Queries)(nil)
