// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: campaigns.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createCampaign = `-- name: CreateCampaign :one
insert into
    campaigns (
        name,
        status,
        budget,
        target_url,
        start_date,
        end_date,
        last_update
    )
values
    ($1, $2, $3, $4::text, $5, $6, now()) 
    returning 
    id,
    name,
    status,
    budget,
    target_url,
    start_date,
    end_date,
    last_update
`

type CreateCampaignParams struct {
	Name      string       `json:"name"`
	Status    string       `json:"status"`
	Budget    string       `json:"budget"`
	Column4   string       `json:"column_4"`
	StartDate time.Time    `json:"start_date"`
	EndDate   sql.NullTime `json:"end_date"`
}

type CreateCampaignRow struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	Status     string       `json:"status"`
	Budget     string       `json:"budget"`
	TargetUrl  string       `json:"target_url"`
	StartDate  time.Time    `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
	LastUpdate sql.NullTime `json:"last_update"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, createCampaign,
		arg.Name,
		arg.Status,
		arg.Budget,
		arg.Column4,
		arg.StartDate,
		arg.EndDate,
	)
	var i CreateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Budget,
		&i.TargetUrl,
		&i.StartDate,
		&i.EndDate,
		&i.LastUpdate,
	)
	return i, err
}

const getAllCampaigns = `-- name: GetAllCampaigns :many
select
    id,
    name,
    status,
    budget,
    target_url,
    start_date,
    end_date,
    last_update
from
    campaigns
order by id
`

type GetAllCampaignsRow struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	Status     string       `json:"status"`
	Budget     string       `json:"budget"`
	TargetUrl  string       `json:"target_url"`
	StartDate  time.Time    `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
	LastUpdate sql.NullTime `json:"last_update"`
}

func (q *Queries) GetAllCampaigns(ctx context.Context) ([]GetAllCampaignsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllCampaigns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllCampaignsRow{}
	for rows.Next() {
		var i GetAllCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Status,
			&i.Budget,
			&i.TargetUrl,
			&i.StartDate,
			&i.EndDate,
			&i.LastUpdate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCampaign = `-- name: GetCampaign :one
select
    id,
    name,
    status,
    budget,
    target_url,
    start_date,
    end_date,
    last_update
from
    campaigns
where
    id = $1
`

type GetCampaignRow struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	Status     string       `json:"status"`
	Budget     string       `json:"budget"`
	TargetUrl  string       `json:"target_url"`
	StartDate  time.Time    `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
	LastUpdate sql.NullTime `json:"last_update"`
}

func (q *Queries) GetCampaign(ctx context.Context, id int64) (GetCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, getCampaign, id)
	var i GetCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Budget,
		&i.TargetUrl,
		&i.StartDate,
		&i.EndDate,
		&i.LastUpdate,
	)
	return i, err
}

const updateCampaign = `-- name: UpdateCampaign :one
update
    campaigns
set
    name = coalesce($1, name),
    status = coalesce($2, status),
    budget = coalesce($3, budget),
    target_url = coalesce($4::text, target_url),
    start_date = coalesce($5, start_date),
    end_date = coalesce($6, end_date),
    last_update = now()
where
    id = $7 returning 
    id,
    name,
    status,
    budget,
    target_url,
    start_date,
    end_date,
    last_update
`

type UpdateCampaignParams struct {
	NewName      sql.NullString `json:"new_name"`
	NewStatus    sql.NullString `json:"new_status"`
	NewBudget    sql.NullString `json:"new_budget"`
	NewTargetUrl sql.NullString `json:"new_target_url"`
	NewStartDate sql.NullTime   `json:"new_start_date"`
	NewEndDate   sql.NullTime   `json:"new_end_date"`
	ID           int64          `json:"id"`
}

type UpdateCampaignRow struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	Status     string       `json:"status"`
	Budget     string       `json:"budget"`
	TargetUrl  string       `json:"target_url"`
	StartDate  time.Time    `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
	LastUpdate sql.NullTime `json:"last_update"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (UpdateCampaignRow, error) {
	row := q.db.QueryRowContext(ctx, updateCampaign,
		arg.NewName,
		arg.NewStatus,
		arg.NewBudget,
		arg.NewTargetUrl,
		arg.NewStartDate,
		arg.NewEndDate,
		arg.ID,
	)
	var i UpdateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Status,
		&i.Budget,
		&i.TargetUrl,
		&i.StartDate,
		&i.EndDate,
		&i.LastUpdate,
	)
	return i, err
}
