// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: convesrion_event.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

const createConversionEvent = `-- name: CreateConversionEvent :one

insert into conversion_event
(

    campaign_id,
    occurred_at,
    amount

) values ($1, $2, $3) returning id, campaign_id, occurred_at, amount
`

type CreateConversionEventParams struct {
	CampaignID int64           `json:"campaign_id"`
	OccurredAt time.Time       `json:"occurred_at"`
	Amount     decimal.Decimal `json:"amount"`
}

func (q *Queries) CreateConversionEvent(ctx context.Context, arg CreateConversionEventParams) (ConversionEvent, error) {
	row := q.db.QueryRowContext(ctx, createConversionEvent, arg.CampaignID, arg.OccurredAt, arg.Amount)
	var i ConversionEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OccurredAt,
		&i.Amount,
	)
	return i, err
}

const getConversion = `-- name: GetConversion :one

select id, campaign_id, occurred_at, amount from  conversion_event
    where id = $1
`

func (q *Queries) GetConversion(ctx context.Context, id int64) (ConversionEvent, error) {
	row := q.db.QueryRowContext(ctx, getConversion, id)
	var i ConversionEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OccurredAt,
		&i.Amount,
	)
	return i, err
}

const upDataConversion = `-- name: UpDataConversion :one

update conversion_event
    set 
        campaign_id =   coalesce($1,campaign_id),
        occurred_at =   coalesce($2,occurred_at),
        amount      =   coalesce($3,     amount)
    where id = $4 returning id, campaign_id, occurred_at, amount
`

type UpDataConversionParams struct {
	NewCampaignID sql.NullInt64   `json:"new_campaign_id"`
	NewOccurredAt sql.NullTime    `json:"new_occurred_at"`
	NewAmount     decimal.Decimal `json:"new_amount"`
	ID            int64           `json:"id"`
}

func (q *Queries) UpDataConversion(ctx context.Context, arg UpDataConversionParams) (ConversionEvent, error) {
	row := q.db.QueryRowContext(ctx, upDataConversion,
		arg.NewCampaignID,
		arg.NewOccurredAt,
		arg.NewAmount,
		arg.ID,
	)
	var i ConversionEvent
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.OccurredAt,
		&i.Amount,
	)
	return i, err
}
