// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_stat.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"

	"github.com/shopspring/decimal"
)

const createDailyStat = `-- name: CreateDailyStat :one

insert into daily_stat(
    campaign_id,
    date_daily,
    impressions,
    clicks,
    cost,
    conversion,
    revenue, 
    reach
) values ($1,$2,$3,$4,$5,$6,$7,$8) returning id, campaign_id, date_daily, impressions, clicks,  cost, conversion, revenue, reach
`

type CreateDailyStatParams struct {
	CampaignID  int64           `json:"campaign_id"`
	DateDaily   time.Time       `json:"date_daily"`
	Impressions int64           `json:"impressions"`
	Clicks      int64           `json:"clicks"`
	Cost        decimal.Decimal `json:"cost"`
	Conversion  sql.NullInt32   `json:"conversion"`
	Revenue     decimal.Decimal `json:"revenue"`
	Reach       int64           `json:"reach"`
}

func (q *Queries) CreateDailyStat(ctx context.Context, arg CreateDailyStatParams) (DailyStat, error) {
	row := q.db.QueryRowContext(ctx, createDailyStat,
		arg.CampaignID,
		arg.DateDaily,
		arg.Impressions,
		arg.Clicks,
		arg.Cost,
		arg.Conversion,
		arg.Revenue,
		arg.Reach,
	)
	var i DailyStat
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DateDaily,
		&i.Impressions,
		&i.Clicks,
		&i.Cost,
		&i.Conversion,
		&i.Revenue,
		&i.Reach,
	)
	return i, err
}

const getDaily = `-- name: GetDaily :one
    select  id,campaign_id, date_daily, impressions,
    clicks,
    cost,
    conversion,
    revenue, 
    reach from daily_stat
    where id = $1
`

func (q *Queries) GetDaily(ctx context.Context, id int64) (DailyStat, error) {
	row := q.db.QueryRowContext(ctx, getDaily, id)
	var i DailyStat
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DateDaily,
		&i.Impressions,
		&i.Clicks,
		&i.Cost,
		&i.Conversion,
		&i.Revenue,
		&i.Reach,
	)
	return i, err
}

const getDailys = `-- name: GetDailys :many

select  id,campaign_id, date_daily, impressions,
    clicks,
    cost,
    conversion,
    revenue, 
    reach from daily_stat
    order by id
    limit $1 offset $2
`

type GetDailysParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetDailys(ctx context.Context, arg GetDailysParams) ([]DailyStat, error) {
	rows, err := q.db.QueryContext(ctx, getDailys, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailyStat{}
	for rows.Next() {
		var i DailyStat
		if err := rows.Scan(
			&i.ID,
			&i.CampaignID,
			&i.DateDaily,
			&i.Impressions,
			&i.Clicks,
			&i.Cost,
			&i.Conversion,
			&i.Revenue,
			&i.Reach,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDaily = `-- name: UpdateDaily :one
    update daily_stat
    set 
        campaign_id =   coalesce($1, campaign_id),
        date_daily  =   coalesce($2,      date_daily),
        impressions =   coalesce($3,     impressions),
        clicks      =   coalesce($4,          clicks),
        cost        =   coalesce($5,            cost),
        conversion  =   coalesce($6,      conversion),
        revenue     =   coalesce($7,         revenue),
        reach       =   coalesce($8,           reach)
where 
    id = $9 returning id, campaign_id, date_daily, impressions, clicks,  cost, conversion, revenue, reach
`

type UpdateDailyParams struct {
	NewCampaignID sql.NullInt64   `json:"new_campaign_id"`
	DateDaily     sql.NullTime    `json:"date_daily"`
	Impressions   sql.NullInt64   `json:"impressions"`
	Clicks        sql.NullInt64   `json:"clicks"`
	Cost          decimal.Decimal `json:"cost"`
	Conversion    sql.NullInt32   `json:"conversion"`
	Revenue       decimal.Decimal `json:"revenue"`
	Reach         sql.NullInt64   `json:"reach"`
	ID            int64           `json:"id"`
}

func (q *Queries) UpdateDaily(ctx context.Context, arg UpdateDailyParams) (DailyStat, error) {
	row := q.db.QueryRowContext(ctx, updateDaily,
		arg.NewCampaignID,
		arg.DateDaily,
		arg.Impressions,
		arg.Clicks,
		arg.Cost,
		arg.Conversion,
		arg.Revenue,
		arg.Reach,
		arg.ID,
	)
	var i DailyStat
	err := row.Scan(
		&i.ID,
		&i.CampaignID,
		&i.DateDaily,
		&i.Impressions,
		&i.Clicks,
		&i.Cost,
		&i.Conversion,
		&i.Revenue,
		&i.Reach,
	)
	return i, err
}
