// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
	"time"
)

type Campaign struct {
	ID         int64        `json:"id"`
	Name       string       `json:"name"`
	Status     string       `json:"status"`
	CreatedAt  time.Time    `json:"created_at"`
	Budget     string       `json:"budget"`
	TargetUrl  string       `json:"target_url"`
	StartDate  time.Time    `json:"start_date"`
	EndDate    sql.NullTime `json:"end_date"`
	LastUpdate sql.NullTime `json:"last_update"`
}

type ConversionEvent struct {
	ID         int64     `json:"id"`
	CampaignID int64     `json:"campaign_id"`
	OccurredAt time.Time `json:"occurred_at"`
	// can be negative or positive
	Amount sql.NullString `json:"amount"`
}

type DailyStat struct {
	ID          int64          `json:"id"`
	CampaignID  int64          `json:"campaign_id"`
	Dates       time.Time      `json:"dates"`
	Impressions int64          `json:"impressions"`
	Clicks      int64          `json:"clicks"`
	Cost        string         `json:"cost"`
	Conversion  sql.NullInt32  `json:"conversion"`
	Revenue     sql.NullString `json:"revenue"`
}

type User struct {
	ID           int64     `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}
