// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error)
	CreateConversionEvent(ctx context.Context, arg CreateConversionEventParams) (ConversionEvent, error)
	CreateDailyStat(ctx context.Context, arg CreateDailyStatParams) (DailyStat, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAllCampaigns(ctx context.Context) ([]GetAllCampaignsRow, error)
	GetCampaign(ctx context.Context, id int64) (GetCampaignRow, error)
	GetConversion(ctx context.Context, id int64) (ConversionEvent, error)
	GetDaily(ctx context.Context, id int64) (DailyStat, error)
	GetDailys(ctx context.Context, arg GetDailysParams) ([]DailyStat, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	UpDataConversion(ctx context.Context, arg UpDataConversionParams) (ConversionEvent, error)
	UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (UpdateCampaignRow, error)
	UpdateDaily(ctx context.Context, arg UpdateDailyParams) (DailyStat, error)
	UpвateUsers(ctx context.Context, arg UpвateUsersParams) (User, error)
}

var _ Querier = (*Queries)(nil)
