// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
insert into users (
    email,
    password_hash
) values (
    $1, $2
) returning id, email, password_hash, created_at
`

type CreateUserParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, password_hash, created_at from users
where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const upвateUsers = `-- name: UpвateUsers :one

update users
set 
    password_hash = coalesce($1, password_hash),
    email = coalesce($2, email)
where 
    email = $3
returning id, email, password_hash, created_at
`

type UpвateUsersParams struct {
	NewPasswordHash sql.NullString `json:"new_password_hash"`
	NewEmail        sql.NullString `json:"new_email"`
	TargetEmail     string         `json:"target_email"`
}

func (q *Queries) UpвateUsers(ctx context.Context, arg UpвateUsersParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upвateUsers, arg.NewPasswordHash, arg.NewEmail, arg.TargetEmail)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}
